# Generated by Django 4.2 on 2023-04-13 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='crypto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.coin'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='cryptos',
            field=models.ManyToManyField(through='accounts.Holding', to='pages.coin'),
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
